POST  http://localhost:3333/videos
Content-Type: application/json
# Accept-Language: pt

{
   "title" :"video 02",
   "description": "Esse 2º video",
   "duration": 190
}


###


GET   http://localhost:3333/videos?search=02

####

GET   http://localhost:3333/videos
  

###
PUT   http://localhost:3333/videos/89e77325-9ec3-49fb-a809-23e2e26026ec
Content-Type: application/json
Accept-Language: pt

{
    "title" :"video 022",
    "description": "update vid02",
    "duration":200 
}

###

DELETE http://localhost:3333/videos/09841104-91d2-4ed2-846e-43a176be481d